version: "3.9"
   
services:
  mongodb:
    image: mongodb/mongodb-community-server:4.4-ubuntu2004
    ports:
      - 6000:27017
    env_file:
      - .env
    volumes:
      - watchdog:/data/db
    command: --bind_ip_all
  
  redis:
    image: redis:latest
    ports:
      - 6001:6379

  discord:
    build: 
      dockerfile: discord.Dockerfile
  
  tracking:
    build:
      dockerfile: tracking.Dockerfile
  
  scheduler:
    build:
      dockerfile: scheduler.Dockerfile

volumes:
  watchdog: